#!/usr/bin/env perl
use strict;
use warnings;
use ConfigReader::Simple;
use Getopt::Long;
use Pod::Usage;

my $config_file = $ENV{'HOME'} . '/.autostow/autostow.cfg';
my $config =
  ConfigReader::Simple->new_multiple(
    Files => [ "$config_file", '/etc/autostow.cfg' ] );

my $template_dir = $config->get('template_dir');

my $man     = 0;
my $help    = 0;
my $verbose = 0;

my $template;
my $software_package;
my $version;

my $result = GetOptions(
    "template=s" => \$template,
    "package=s"  => \$software_package,
    "version=s"  => \$version,
    "verbose"    => \$verbose,
    'help|?'     => \$help
);

unless ( defined $template && defined $software_package && defined $version ) {
    &print_available_templates();
    pod2usage(1);
}

my $stow_script = &process_template($template);
open( STOWFILE, ">stow-$software_package-$version" ) || die;
print STOWFILE $stow_script;
close STOWFILE;

sub process_template {
    my $template_file = shift;
    $template_file = $ENV{'HOME'} . "/.autostow/templates/$template_file";
    #    $template_file = "$template_dir/$template_file";
    open( TEMPLATE, "<$template_file" ) || die;
    undef $/;    # 'slurp' mode
    my $whole_file = <TEMPLATE>;
    $whole_file =~ s/VERSION=DO_NOT_EDIT/VERSION=\"$version"/;
    $whole_file =~ s/PACKAGE=DO_NOT_EDIT/PACKAGE=\"$software_package"/;
    return $whole_file;
}

sub display_ruby_info {
    
}

sub print_available_templates {
    print <<END;
Templates distributed with Autostow:
    gnu.tmpl        => GNU build system, DESTDIR=/usr/local, Stow dir=/usr/local/stow
    cmake.tmpl      => Cmake build system, DESTDIR=/usr/local, Stow dir=/usr/local/stow
    perl.tmpl       => Perl module, DESTDIR=/usr/local, Stow dir=/usr/local/stow
    --
    gnu-root.tmpl   => GNU build system, DESTDIR=/usr, Stow dir=/stow
    cmake-root.tmpl => Cmake build system, DESTDIR=/usr, Stow dir=/stow
    perl-root.tmpl  => Perl module, DESTDIR=/usr, Stow Dir=/stow
    rubygem-root.tmpl  => Ruby Gems, DESTDIR=/usr, Stow Dir=/stow

END
}

__END__

=head1 NAME

autostow - A program to generate configure, build and stow scripts

=head1 SYNOPSIS

    autostow --package=package --template=template --version=version

Examples:

    autostow --package=emacs --template=gnu.tmpl --version=22.3

    autostow --package=DBI --template=perl.tmpl --version=1.609
