#!/bin/bash
set -o errexit
PACKAGE=DO_NOT_EDIT
VERSION=DO_NOT_EDIT
PACKAGER="TDW <troydwill@gmail.com>"
# PACKAGER="JS <Jane_Smith@fsf.org>"
DATE="2010-04-12"
HOMEPAGE_URL=""
SOURCE_URL=""
PREFIX="/usr"
TARGET="/"
STOW_DIR="/stow"
SUDO="sudo"

PACKAGE_DIR=${PACKAGE}-${VERSION}

continue_prompt () {
    echo "Ctrl-c to quit, Enter to continue"
    read
}

do_configure () {
    perl ./Build.PL PREFIX=${PREFIX} 2>&1 | tee log.stow.configure.${PACKAGE}-${VERSION}
}

do_build () {
    perl ./Build 2>&1 | tee log.stow.Build.${PACKAGE}-${VERSION}
}

do_test () {
    perl ./Build test 2>&1 | tee log.stow.Build.test.${PACKAGE}-${VERSION}
}

do_install () {
    ${SUDO} ./Build --destdir ${STOW_DIR}/${PACKAGE_DIR} install 2>&1 | tee log.stow.install.${PACKAGE}-${VERSION}
}

do_stow () {
    ${SUDO} find ${STOW_DIR}/${PACKAGE_DIR} -name 'perllocal.pod' -okdir mv -v '{}' perllocal.pod.stow.${PACKAGE}-${VERSION} ';'
    ${SUDO} stow -v --target=${TARGET} --dir=${STOW_DIR} ${PACKAGE_DIR} 2>&1 | tee log.stow.stow.${PACKAGE}-${VERSION}
}

do_package () {
    TARBALL="${PACKAGE_DIR}.stow.tar.bz2"
    cd ${STOW_DIR}
    ${SUDO} tar -jcf ${TARBALL} ${PACKAGE_DIR}
    ${SUDO} mv --verbose ${TARBALL} /tmp
}

do_configure && continue_prompt
do_build && continue_prompt
do_test && continue_prompt
do_install && continue_prompt
do_stow && continue_prompt
do_package && continue_prompt
